config/routes.rb
Rails.application.routes.draw do
  devise_for :users
    root to: 'pages#home'
   get 'widget', to: 'widgets#widget'
   get 'widget_2', to: 'widgets#widget_2'
   get 'test_widget', to: 'widgets#test_widget'

   resources :leads , only: [:index, :show, :new, :destroy, :create ]
   #
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lead.rb
class Lead < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :accounts, foreign_key: :owner_id
  has_many :leads
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/leads_controller.rb
require 'rest-client'



class LeadsController < ApplicationController
  # skip_before_action :authenticate_user!, only: [:home]
 skip_before_action :verify_authenticity_token, :authenticate_user!
 after_action :allow_iframe
 # after_create :send_welcome_email
  # layout 'widget_layout'

def index
  @lead = Lead.new
  respond_to do |format|
        format.html do
          # load data to show in the view
          # @data = ...
          render :widget
        end
        format.js do
          render :widget
        end
      end

  end


def show
end


    def new
    @lead = Lead.new
    respond_to do |format|
          format.html do
            # load data to show in the view
            # @data = ...
            render :widget
          end
          format.js do
            render :widget
          end
        end

    end


  def create
    @lead = Lead.new(lead_params)
    # @lead.user_id = 1
    @lead.user_id = params[:user_id]
    params[:lead][:rgpd] == "1" ? @lead.rgpd = true : @lead.rgpd = false
    @lead.save
    render template: "leads/result_submit", layout: false
    # email = @lead
    UserMailer.welcome(@lead).deliver_now



    # @lead.each do |elem|

      # next if elem[:email].nil? || (elem[:email] == " ")
      def hubspot_post


      url_user = 'https://api.hsforms.com/submissions/v3/integration/submit/5187319/1072b70c-a9b7-41ef-8a50-4dc62698cc52'
      @response = RestClient.post url_user,
      {
    "fields": [
      {
        "name": "firstname",
        "value": @lead.first_name
      },
      {
        "name": "lastname",
        "value": @lead.last_name
      },
      {
        "name": "email",
        "value": @lead.email
      },
      {
        "name": "city",
        "value": @lead.city
      },
      {
        "name": "company",
        "value": @lead.company
      },
      {
        "name": "zip",
        "value": @lead.zip
      },
      {
        "name": "address",
        "value": @lead.address
      }
    ],

      "legalConsentOptions":{
        "consent":{
          "consentToProcess":true,
          "text":"I agree to allow Example Company to store and process my personal data.",
          "communications":[
            {
              "value":true,
              "subscriptionTypeId":999,
              "text":"I agree to receive marketing communications from Example Company."
            }
          ]
        }
      }
  }.to_json, {content_type: :json, accept: :json}

      end
      # end



    # {

    #   "fields": [
    #     {
    #       "name": "email",
    #       "value": "frefre@example.com"
    #     },
    #     {
    #       "name": "firstname",
    #       "value": "fefre"
    #     },
    #     {
    #       "name": "lastname",
    #       "value": "dodo"
    #     }
    #   ],

    #   "legalConsentOptions":{
    #     "consent":{
    #       "consentToProcess":true,
    #       "text":"I agree to allow Example Company to store and process my personal data.",
    #       "communications":[
    #         {
    #           "value":true,
    #           "subscriptionTypeId":999,
    #           "text":"I agree to receive marketing communications from Example Company."
    #         }
    #       ]
    #     }
    #   }
    # }


    # Unless @lead.valid?, #save will return false,
    # and @lead is not persisted.
    # TODO: present the form again with error messages.
    # redirect_to home_path(@lead)
  end

  private

  def allow_iframe
    response.headers.except! 'X-Frame-Options'
  end


  def send_welcome_email
    UserMailer.welcome.deliver_now
  end

  def lead_params
    params.require(:lead).permit(:first_name, :last_name, :address, :address_2, :email, :zip, :company, :city, :user_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :verify_authenticity_token, :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
  skip_before_action :verify_authenticity_token, :authenticate_user!
  after_action :allow_iframe
  # layout 'widget_layout', only: [:widget]
  # layout 'widget_layout_2', only: [:widget_2]

  def widget
    @lead = Lead.new
    respond_to do |format|
      format.html do
        # load data to show in the view
        # @data = ...
        render :widget, :layout => 'widget_layout'
      end
      format.js do
        render :widget
      end
    end
  end

    def widget_2
    @lead = Lead.new
    respond_to do |format|
      format.html do
        # load data to show in the view
        # @data = ...
        render :widget_2, :layout => 'widget_layout_2'
      end
      format.js do
        render :widget_2
      end
    end
  end

  def test_widget
    render :test_widget, layout: false
  end

  private

  def allow_iframe
    response.headers.except! 'X-Frame-Options'
  end

  def get_rumours
    if params[:id]
      Rumour.displayed.where(id: params[:id])
    else
      Rails.cache.fetch('rumours_for_widget', expires_in: 5.minutes) do
       Rumour.order(timestamp: :desc).displayed.limit(5)
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>

  </body>
</html>

app/views/layouts/widget_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>My Widget</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
<link rel="stylesheet" href="//cdn2.hubspot.net/hub/2504184/hub_generated/template_assets/1560867303599/Catalogue_Templates/Page/Frederic/autocomplete_LP.min.css" type="text/css" />
  <%# stylesheet_link_tag 'widgets.css', media: 'all' %> <!-- Have custom CSS? -->
  <link href="/assets/widgets.scss" media="all" rel="stylesheet" />

<script src="https://cdn.jsdelivr.net/npm/places.js@1.16.4"></script>
<script type="text/javascript" id="hs-script-loader" async defer src="//js.hs-scripts.com/5187319.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js" type="text/javascript"></script>
<!-- start Mixpanel --><script type="text/javascript">(function(c,a){if(!a.__SV){var b=window;try{var d,m,j,k=b.location,f=k.hash;d=function(a,b){return(m=a.match(RegExp(b+"=([^&]*)")))?m[1]:null};f&&d(f,"state")&&(j=JSON.parse(decodeURIComponent(d(f,"state"))),"mpeditor"===j.action&&(b.sessionStorage.setItem("_mpcehash",f),history.replaceState(j.desiredHash||"",c.title,k.pathname+k.search)))}catch(n){}var l,h;window.mixpanel=a;a._i=[];a.init=function(b,d,g){function c(b,i){var a=i.split(".");2==a.length&&(b=b[a[0]],i=a[1]);b[i]=function(){b.push([i].concat(Array.prototype.slice.call(arguments,
0)))}}var e=a;"undefined"!==typeof g?e=a[g]=[]:g="mixpanel";e.people=e.people||[];e.toString=function(b){var a="mixpanel";"mixpanel"!==g&&(a+="."+g);b||(a+=" (stub)");return a};e.people.toString=function(){return e.toString(1)+".people (stub)"};l="disable time_event track track_pageview track_links track_forms track_with_groups add_group set_group remove_group register register_once alias unregister identify name_tag set_config reset opt_in_tracking opt_out_tracking has_opted_in_tracking has_opted_out_tracking clear_opt_in_out_tracking people.set people.set_once people.unset people.increment people.append people.union people.track_charge people.clear_charges people.delete_user people.remove".split(" ");
for(h=0;h<l.length;h++)c(e,l[h]);var f="set set_once union unset remove delete".split(" ");e.get_group=function(){function a(c){b[c]=function(){call2_args=arguments;call2=[c].concat(Array.prototype.slice.call(call2_args,0));e.push([d,call2])}}for(var b={},d=["get_group"].concat(Array.prototype.slice.call(arguments,0)),c=0;c<f.length;c++)a(f[c]);return b};a._i.push([b,d,g])};a.__SV=1.2;b=c.createElement("script");b.type="text/javascript";b.async=!0;b.src="undefined"!==typeof MIXPANEL_CUSTOM_LIB_URL?
MIXPANEL_CUSTOM_LIB_URL:"file:"===c.location.protocol&&"//cdn4.mxpnl.com/libs/mixpanel-2-latest.min.js".match(/^\/\//)?"https://cdn4.mxpnl.com/libs/mixpanel-2-latest.min.js":"//cdn4.mxpnl.com/libs/mixpanel-2-latest.min.js";d=c.getElementsByTagName("script")[0];d.parentNode.insertBefore(b,d)}})(document,window.mixpanel||[]);
mixpanel.init("8ac784cd197016d4e37f3bffaeca79dc");</script><!-- end Mixpanel -->

<!-- <script src="path/to/jquery.easy-autocomplete.min.js"></script>
<link rel="stylesheet" href="path/to/easy-autocomplete.min.css"> -->
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/layouts/widget_layout_2.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>My Widget</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
<link rel="stylesheet" href="//cdn2.hubspot.net/hub/2504184/hub_generated/template_assets/1560867303599/Catalogue_Templates/Page/Frederic/autocomplete_LP.min.css" type="text/css" />
  <%# stylesheet_link_tag 'widgets.css', media: 'all' %> <!-- Have custom CSS? -->
  <link href="/assets/widgets_2.scss" media="all" rel="stylesheet" />

<script src="https://cdn.jsdelivr.net/npm/places.js@1.16.4"></script>
<script type="text/javascript" id="hs-script-loader" async defer src="//js.hs-scripts.com/5187319.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js" type="text/javascript"></script>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/leads/index.html.erb
<div id="my-widget"></div>
<script src="http://localhost:3000/widget.js" type="text/javascript"></script>

app/views/leads/result_submit.html.erb
<h1>Merci</h1>

app/views/pages/home.html.erb
<div id="my-widget"></div>
<script src="http://localhost:3000/widget.js" type="text/javascript"></script>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/widgets/widget.js.erb
var MyWidgetJS = {
  getScript: function(url, success) {
    var done, head, script;
    script = document.createElement('script');
    script.src = url;
    head = document.getElementsByTagName('head')[0];
    done = false;
    script.onload = script.onreadystatechange = function() {
      if (!done && (!this.readyState || this.readyState === 'loaded' || this.readyState === 'complete')) {
        done = true;
        success();
        script.onload = script.onreadystatechange = null;
        return head.removeChild(script);
      }
    };
    return head.appendChild(script);
  },
  load: function() {
    var $elem, $iframe;
    $elem = $('#my-widget');
    var url = "<%= widget_url %>";
    if ($elem.length > 0) {
      $elem.empty();
      $iframe = $('<iframe>').attr('src',  url)
                             .attr('frameborder', '0')
                             .attr('id', 'widget-iframe')
                             .attr('allowtransparency', 'true');
      return $elem.append($iframe);
    }
  },
};
if (typeof jQuery === 'undefined') {
  MyWidgetJS.getScript('//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js', function() {
    return MyWidgetJS.load();
  });
} else {
  MyWidgetJS.load();
}































// var MyWidgetJS = {
//   getScript: function(url, success) {
//     var done, head, script;
//     script = document.createElement('script');
//     script.src = url;
//     head = document.getElementsByTagName('head')[0];
//     done = false;
//     script.onload = script.onreadystatechange = function() {
//       if (!done && (!this.readyState || this.readyState === 'loaded' || this.readyState === 'complete')) {
//         done = true;
//         success();
//         script.onload = script.onreadystatechange = null;
//         return head.removeChild(script);
//       }
//     };
//     //console.log(script.src);
//     return head.appendChild(script);
//   },
//   load: function() {
//     var $elem, $iframe, $form;
//     $elem = $('#my-widget');
//     var url = "<%= widget_url %>";
//     if ($elem.length > 0) {
//       $elem.empty();
//       $iframe = $('<iframe>').attr('src',  url)
//                              .attr('frameborder', '0')
//                              .attr('id', 'widget-iframe')
//                              .attr('allowtransparency', 'true');
//       return $elem.append($iframe);
//     }
//   },
//   algolia: function () {
// // var a = $("#widget-iframe").contents().find("#form-address");
// //  var b = document.querySelector('input')
// var frame = document.getElementById('widget-iframe');
// console.log(frame);
// // var frame_2 = frame.contentDocument || frame.contentWindow.document;
// // console.log(frame_2);
// // var document = frame_2
// // var b = frame_2.getElementById('form-address');
// // console.log(b);


// console.log("je suis ici");

//   var placesAutocomplete = places({
//     appId: 'pl2WBQ5IQ5YB',
//     apiKey: '32f513307ec1b6927f0ad3fc3cfff192',
//  container: document.getElementById("widget-iframe").contentWindow.document.getElementById("form-address"),
//  // style: false,
//     templates: {
//       value: function(suggestion) {
//         return suggestion.name;
//       }
//     }
//   }).configure({
//     type: 'address'
//   });
//   console.log("je suis maintenant ici")
//   placesAutocomplete.on('change', function resultSelected(e) {
//     document.querySelector('#form-address2').value = e.suggestion.administrative || '';
//     document.querySelector('#form-city').value = e.suggestion.city || '';
//     document.querySelector('#form-zip').value = e.suggestion.postcode || '';
//   });
// },
// };
// if (typeof jQuery === 'undefined') {
//   MyWidgetJS.getScript('//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js', function() {
//     return MyWidgetJS.load();
//   });
//    MyWidgetJS.getScript('https://cdn.jsdelivr.net/npm/places.js@1.16.4', function() {
//     return MyWidgetJS.algolia();
//   });
// } else {
//   MyWidgetJS.load();
// }





















































// (function() {

// // Localize jQuery variable
// var jQuery;

// /******** Load jQuery if not present *********/
// if (window.jQuery === undefined || window.jQuery.fn.jquery !== '1.8.3') {
//     var script_tag = document.createElement('script');
//     script_tag.setAttribute("type","text/javascript");
//     script_tag.setAttribute("src",
//         "http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js");
//     var script_tag1 = document.createElement('script');
//     script_tag1.setAttribute("type","text/javascript");
//     script_tag1.setAttribute("src",
//         "https://cdn.jsdelivr.net/npm/places.js@1.16.4");

//     if (script_tag.readyState) {
//       script_tag.onreadystatechange = function () { // For old versions of IE
//           if (this.readyState == 'complete' || this.readyState == 'loaded') {
//               scriptLoadHandler();
//           }
//       };
//     } else { // Other browsers
//       script_tag.onload = scriptLoadHandler;
//     }
//     // Try to find the head, otherwise default to the documentElement
//     (document.getElementsByTagName("head")[0] || document.documentElement).appendChild(script_tag);
//     (document.getElementsByTagName("head")[0] || document.documentElement).appendChild(script_tag1);
// } else {
//     // The jQuery version on the window is the one we want to use
//     jQuery = window.jQuery;
//     main();
// }

// /******** Called once jQuery has loaded ******/
// function scriptLoadHandler() {
//     // Restore $ and window.jQuery to their previous values and store the
//     // new jQuery in our local jQuery variable
//     jQuery = window.jQuery.noConflict(true);
//     // Call our main function
//     main();
// }

// /******** Our main function ********/
// function main() {
//     jQuery(document).ready(function($) {
//     /******* Load CSS *******/
//     var css_link = $("<link>", {
//             rel: "stylesheet",
//             type: "text/css",
//             href: "http://localhost:3000/widgets_layout"
//         });
//         css_link.appendTo('head');
//         var txt;
//         txt='<div id="wrapper">';
//         txt=txt+'<ul class="tabs">';
//         txt=txt+'<li id="fixtures_tab"><a href="#fixtures">Hepsi</a></li>';
//         txt=txt+'<li id="live_tab"><a href="#live">Canlı</a></li>';
//         txt=txt+'<li id="finished_tab"><a href="#finished">Bitmiş</a></li>';
//         txt=txt+'<li id="program_tab"><a href="#program">Başlamamış</a></li>';
//         txt=txt+'<li id="postpond_tab"><a href="#postpond">Ertelenen</a></li>';
//         txt=txt+'<li id="selected_tab"><a id="f" href="#fav">Oyunlarım (0)</a></li>';
//         txt=txt+'</ul>';
//         txt=txt+'<div class="tab-container">';
//         txt=txt+'<div id="fixtures" class="tab-content"><script type="text/javascript">get_All_Today_Matches();</script></div>';
//         txt=txt+'<div id="live" class="tab-content"><script type="text/javascript"></script></div>';
//         txt=txt+'<div id="finished" class="tab-content"><script type="text/javascript"></script></div>';
//         txt=txt+'<div id="program" class="tab-content"><script type="text/javascript"></script></div>';
//         txt=txt+'<div id="postpond" class="tab-content"><script type="text/javascript"></script></div>';
//         txt=txt+'<div id="fav" class="tab-content"><script type="text/javascript"></script></div>';
//         txt=txt+'</div>';
//         txt=txt+'</div>';
//         $('#widget-container').html(txt);
//     });
// }
// })(); // We call our anonymous function immediately

// setTimeout(function(){
// var timer = $.timer(function() {
//     var cha = "'";
//     $('.show_hide').html("");
//     setTimeout(function(){
//         $('.show_hide').html(cha);
//     }, 500);
// });
// timer.set({ time : 1000, autostart : true });
// }, 3000);

app/views/widgets/widget_2.js.erb
var MyWidgetJS = {
  getScript: function(url, success) {
    var done, head, script;
    script = document.createElement('script');
    script.src = url;
    head = document.getElementsByTagName('head')[0];
    done = false;
    script.onload = script.onreadystatechange = function() {
      if (!done && (!this.readyState || this.readyState === 'loaded' || this.readyState === 'complete')) {
        done = true;
        success();
        script.onload = script.onreadystatechange = null;
        return head.removeChild(script);
      }
    };
    return head.appendChild(script);
  },
  load: function() {
    var $elem, $iframe;
    $elem = $('#my-widget');
    var url = "<%= widget_2_url %>";
    if ($elem.length > 0) {
      $elem.empty();
      $iframe = $('<iframe>').attr('src',  url)
                             .attr('frameborder', '0')
                             .attr('id', 'widget-iframe')
                             .attr('allowtransparency', 'true');
      return $elem.append($iframe);
    }
  },
};
if (typeof jQuery === 'undefined') {
  MyWidgetJS.getScript('//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js', function() {
    return MyWidgetJS.load();
  });
} else {
  MyWidgetJS.load();
}































// var MyWidgetJS = {
//   getScript: function(url, success) {
//     var done, head, script;
//     script = document.createElement('script');
//     script.src = url;
//     head = document.getElementsByTagName('head')[0];
//     done = false;
//     script.onload = script.onreadystatechange = function() {
//       if (!done && (!this.readyState || this.readyState === 'loaded' || this.readyState === 'complete')) {
//         done = true;
//         success();
//         script.onload = script.onreadystatechange = null;
//         return head.removeChild(script);
//       }
//     };
//     //console.log(script.src);
//     return head.appendChild(script);
//   },
//   load: function() {
//     var $elem, $iframe, $form;
//     $elem = $('#my-widget');
//     var url = "<%= widget_url %>";
//     if ($elem.length > 0) {
//       $elem.empty();
//       $iframe = $('<iframe>').attr('src',  url)
//                              .attr('frameborder', '0')
//                              .attr('id', 'widget-iframe')
//                              .attr('allowtransparency', 'true');
//       return $elem.append($iframe);
//     }
//   },
//   algolia: function () {
// // var a = $("#widget-iframe").contents().find("#form-address");
// //  var b = document.querySelector('input')
// var frame = document.getElementById('widget-iframe');
// console.log(frame);
// // var frame_2 = frame.contentDocument || frame.contentWindow.document;
// // console.log(frame_2);
// // var document = frame_2
// // var b = frame_2.getElementById('form-address');
// // console.log(b);


// console.log("je suis ici");

//   var placesAutocomplete = places({
//     appId: 'pl2WBQ5IQ5YB',
//     apiKey: '32f513307ec1b6927f0ad3fc3cfff192',
//  container: document.getElementById("widget-iframe").contentWindow.document.getElementById("form-address"),
//  // style: false,
//     templates: {
//       value: function(suggestion) {
//         return suggestion.name;
//       }
//     }
//   }).configure({
//     type: 'address'
//   });
//   console.log("je suis maintenant ici")
//   placesAutocomplete.on('change', function resultSelected(e) {
//     document.querySelector('#form-address2').value = e.suggestion.administrative || '';
//     document.querySelector('#form-city').value = e.suggestion.city || '';
//     document.querySelector('#form-zip').value = e.suggestion.postcode || '';
//   });
// },
// };
// if (typeof jQuery === 'undefined') {
//   MyWidgetJS.getScript('//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js', function() {
//     return MyWidgetJS.load();
//   });
//    MyWidgetJS.getScript('https://cdn.jsdelivr.net/npm/places.js@1.16.4', function() {
//     return MyWidgetJS.algolia();
//   });
// } else {
//   MyWidgetJS.load();
// }





















































// (function() {

// // Localize jQuery variable
// var jQuery;

// /******** Load jQuery if not present *********/
// if (window.jQuery === undefined || window.jQuery.fn.jquery !== '1.8.3') {
//     var script_tag = document.createElement('script');
//     script_tag.setAttribute("type","text/javascript");
//     script_tag.setAttribute("src",
//         "http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js");
//     var script_tag1 = document.createElement('script');
//     script_tag1.setAttribute("type","text/javascript");
//     script_tag1.setAttribute("src",
//         "https://cdn.jsdelivr.net/npm/places.js@1.16.4");

//     if (script_tag.readyState) {
//       script_tag.onreadystatechange = function () { // For old versions of IE
//           if (this.readyState == 'complete' || this.readyState == 'loaded') {
//               scriptLoadHandler();
//           }
//       };
//     } else { // Other browsers
//       script_tag.onload = scriptLoadHandler;
//     }
//     // Try to find the head, otherwise default to the documentElement
//     (document.getElementsByTagName("head")[0] || document.documentElement).appendChild(script_tag);
//     (document.getElementsByTagName("head")[0] || document.documentElement).appendChild(script_tag1);
// } else {
//     // The jQuery version on the window is the one we want to use
//     jQuery = window.jQuery;
//     main();
// }

// /******** Called once jQuery has loaded ******/
// function scriptLoadHandler() {
//     // Restore $ and window.jQuery to their previous values and store the
//     // new jQuery in our local jQuery variable
//     jQuery = window.jQuery.noConflict(true);
//     // Call our main function
//     main();
// }

// /******** Our main function ********/
// function main() {
//     jQuery(document).ready(function($) {
//     /******* Load CSS *******/
//     var css_link = $("<link>", {
//             rel: "stylesheet",
//             type: "text/css",
//             href: "http://localhost:3000/widgets_layout"
//         });
//         css_link.appendTo('head');
//         var txt;
//         txt='<div id="wrapper">';
//         txt=txt+'<ul class="tabs">';
//         txt=txt+'<li id="fixtures_tab"><a href="#fixtures">Hepsi</a></li>';
//         txt=txt+'<li id="live_tab"><a href="#live">Canlı</a></li>';
//         txt=txt+'<li id="finished_tab"><a href="#finished">Bitmiş</a></li>';
//         txt=txt+'<li id="program_tab"><a href="#program">Başlamamış</a></li>';
//         txt=txt+'<li id="postpond_tab"><a href="#postpond">Ertelenen</a></li>';
//         txt=txt+'<li id="selected_tab"><a id="f" href="#fav">Oyunlarım (0)</a></li>';
//         txt=txt+'</ul>';
//         txt=txt+'<div class="tab-container">';
//         txt=txt+'<div id="fixtures" class="tab-content"><script type="text/javascript">get_All_Today_Matches();</script></div>';
//         txt=txt+'<div id="live" class="tab-content"><script type="text/javascript"></script></div>';
//         txt=txt+'<div id="finished" class="tab-content"><script type="text/javascript"></script></div>';
//         txt=txt+'<div id="program" class="tab-content"><script type="text/javascript"></script></div>';
//         txt=txt+'<div id="postpond" class="tab-content"><script type="text/javascript"></script></div>';
//         txt=txt+'<div id="fav" class="tab-content"><script type="text/javascript"></script></div>';
//         txt=txt+'</div>';
//         txt=txt+'</div>';
//         $('#widget-container').html(txt);
//     });
// }
// })(); // We call our anonymous function immediately

// setTimeout(function(){
// var timer = $.timer(function() {
//     var cha = "'";
//     $('.show_hide').html("");
//     setTimeout(function(){
//         $('.show_hide').html(cha);
//     }, 500);
// });
// timer.set({ time : 1000, autostart : true });
// }, 3000);